sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - "node_modules"

before_deploy:
  - npm run build && rm dist/*.map

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: travis
